config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  root 'home#top'
  get 'home/basic' => 'home#basic'
  
  resources :staffs do
    collection do
    end
  end
  
  resources :menus, only: [:index, :new, :create, :edit, :update, :destroy]
  
  
  resources :schedules, only: [:create, :index] 
  #get 'schedules/:staff_id/new' => 'schedules#new'
  get 'schedules/new' => 'schedules#new'
  get 'schedules/date_workers' => 'schedules#date_workers'
  
  resources :reservations, only: [:destroy, :create, :index] do
    collection do 
      get 'search'
      get 'choose_menus'
      post 'choosen_menus'
      get 'choose_staff'
      get 'choose_date'
      get 'custamer_detail'
      post 'confirm'
    end
    
  end
  
  
  
end

app/models/staff.rb
class Staff < ApplicationRecord
    
    
    has_many :schedules, dependent: :destroy
    has_many :reservations
    mount_uploader :image, ImageUploader
    
    
    with_options presence: true do
        validates :last_name
        validates :first_name
        validates :age
        validates :experience
        validates :gender 
        validates :status
        validates :self_introduction
        validates :image, presence: true
    end
    
    
    validates :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
    validates :first_name_kana, presence: true,format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。'}
    validates :number, presence: true, uniqueness: true

    #シフト作成時のスタッフ選択
    def last_nameANDfirst_name
        
        return '(' + self.number.to_s + ')' + self.last_name + self.first_name
        
    end
    
    scope :active, -> { all }

    # statusカラムを昇順で取得する
    scope :sorted, -> { order(status: :asc) }
    
    # activeとsortedを合わせたもの
    scope :recent, -> { active.sorted }

    
    
    
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
 before_action :basic_auth, if: :production?
 before_action :staff_id_check, only: [:edit, :update, :destroy]
    
    def index
        @staffs = Staff.recent
        @name = '名前'
        @age = '年齢'
        @gender = '性別'
        @status = '階級'
    end
    
    
    def new
        @staff = Staff.new
        
        date = Date.today
        staffIds = Staff.pluck(:id)
        
        if staffIds.present?
            @staff_number = "推奨ナンバー#{date.year}00#{staffIds.last + 1}"
        else
            @staff_number = "推奨ナンバー#{date.year}001"
        end
    end
    
    
    def create
        @staff = Staff.new(staff_params)
        if @staff.save
            flash[:notice] = '社員登録完了しました。'
            redirect_to staffs_path
        else 
            flash.now[:alert] = '社員登録完了していません。'
            render :new
        end
    end
    
    
    def edit
        @staff = searchStaffId
        @staff_image = @staff.image
    end
    

    def update
        
        #else以下が実行された場合 renderが発動するので@staffにしておけば、勝手staffでーたを飛ばしてくれます。
        @staff = searchStaffId

        @staff.assign_attributes(staff_params)
        
        if @staff.save
            flash[:notice] = '社員情報を編集しました。'
            redirect_to staffs_path
            
        else
            flash.now[:alert] = '社員情報を編集できていません。'
            render :edit
            
        end
    end
    
    
    def destroy
        staff = searchStaffId
        staff.destroy
        redirect_to staffs_path
            

    end

    private
        def staff_params
             params.require(:staff).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :number, :age, :gender,
                                           :experience, :status, :self_introduction, :image)
        end


        def staff_id_check
            staff = searchStaffId
            
            if staff.nil?
                flash[:alert] = 'スタッフが存在しません。'
                redirect_to root_path
                
            end
        end
        
        def searchStaffId
            
            Staff.find_by(id: params[:id])
            
        end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
         <div class='staff-form'>
            <div class='field'>
              <%= f.label :社員番号 %><br>
              <i class='font-color'><%= @staff_number %></i>
              <%= f.number_field :number %>
           </div>
           
           <div class='field'>
              <p><%= f.label :苗字 %>
              <%= f.text_field :last_name %>
              
              <%= f.label :名前 %>
              <%= f.text_field :first_name %></p>
               
              <p><%= f.label :苗字（カナ） %>
              <%= f.text_field :last_name_kana %>
              
              <%= f.label :苗字（カナ）%>
              <%= f.text_field :first_name_kana %></p>
           </div>
           
           <div class='field'>
              <%= f.label :年齢 %>
              <%= f.number_field :age %>
           </div>
           
           <div class='field'>
              <%= f.label :性別 %>
              <%= f.radio_button :gender, "男" %><span>M</span> <%= f.radio_button :gender, "女" %><span>F</span>
           </div>
           
           <div class='field'>
              <%= f.label :職歴 %>
              <%= f.select :experience, [ ["1年目","1年目"], ["3年以下","3年以下"], ["6年以下", "6年以下"], 
                                      ["10年以下", "10年以下"], ["10年以上", "10年以上"]], prompt: "職業を選択してください" %>
           </div>
           
           <div class='field'>
              <%= f.label :地位 %>
              <%= f.select :status, [ ["店長", 1], ["副店長", 2], ["スタイリスト", 3]], prompt: "職業を選択してください" %>
           </div>
           
           <div class='field'>
              <%= f.label :自己紹介 %>
              <%= f.text_area :self_introduction %>
           </div>
           
           <div class='staff-image'>
               <%= image_tag @staff_image.to_s %>
            </div>
           
           <div class='field'>
              <%= f.label :画像 %>
              <%= f.file_field :image %>
           </div>
           
            <div class='field'>
              <%= f.submit "登録" %>
            </div>
        </div>

app/views/staffs/edit.html.erb
<%= link_to '管理者画面', home_basic_path%>
<div class='staff-new'>
    <%= form_for @staff do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= render 'form', {:f => f} %>
    <% end %>
</div>

app/views/staffs/index.html.erb
<%= link_to '管理者画面', home_basic_path%>
<div class='staff'>
    <div class='all-staff'>
        <div class='staff-inner'>
            <% @staffs.each do |staff| %>
                <div class='staff-date'>
                    <div class='staff-image'>
                        <%= image_tag staff.image.to_s %>
                    </div>
                    <div class='staff-details'>
                        <p><span><%= @name %></span><%= staff.last_name %><%= staff.first_name %></p>
                        <p><span>カナ</span><%= staff.last_name_kana %><%= staff.first_name_kana %></p>
                        <p><span><%= @age %></span><%= staff.age %></p>
                        <p><span><%= @gender %></span><%= staff.gender %></p>
                        <% case staff.status %>
                            <% when 1 then %>
                                <p><span><%= @status %></span>店長</p>
                            <% when 2 then %>
                                <p><span><%= @status %></span>副店長</p>
                            <% when 3 then %>
                                <p><span><%= @status %></span>スタイリスト</p>
                        <% end %>
                    </div>
                    <div class='staff-introduction'>
                        <p>自己紹介</p>
                        <div class='content'>
                            <%= staff.self_introduction %>
                        </div>
                    </div>
                    <div class='staff-management'>
                        <%= link_to '編集', edit_staff_path(staff.id) %>
                        <%= link_to '削除', staff_path(staff.id), method: :delete, data: { confirm: 'Are you sure?' } %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/staffs/new.html.erb
<%= link_to '管理者画面', home_basic_path%>
<div class='staff-new'>
    <%= form_for @staff do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= render 'form', {:f => f, staff_number: @staff_number} %>
    <% end %>
</div>

<script>

    //render後のリロード対策
    function addToNewUrl() {
        
        //urlを取得
        let path = location.pathname;
        let pattern = "/staffs/new"
    
        // URLが正しければ変更は不要
        if(path.match(pattern)) return;
    
        // URLを変更
        history.replaceState('', '', "/staffs/new" );
    }
    
    window.onload = addToNewUrl();
    
</script>