config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  root 'home#top'
  get 'home/basic' => 'home#basic'
  
  resources :staffs do
    collection do
    end
  end
  
  resources :menus, only: [:index, :new, :create, :edit, :update, :destroy]
  
  
  resources :schedules, only: [:create, :index] 
  #get 'schedules/:staff_id/new' => 'schedules#new'
  get 'schedules/new' => 'schedules#new'
  get 'schedules/date_workers' => 'schedules#date_workers'
  
  resources :reservations, only: [:destroy, :create, :index] do
    collection do 
      get 'search'
      get 'choose_menus'
      post 'choosen_menus'
      get 'choose_staff'
      get 'choose_date'
      get 'custamer_detail'
      post 'confirm'
    end
    
  end
  
  
  
end

app/models/menu.rb
class Menu < ApplicationRecord
    
    require 'active_support/core_ext/numeric/conversions'
    
    with_options presence: true do
        validates :name
        validates :category
        validates :price
        validates :required_time
    end
    

    validates :name, uniqueness: true
    
    validates :price, format: { with: /\A[0-9]+\z/, message: "半角数値のみが使用できます" }
    
    validates :required_time, format: { with: /\A[0-9]+\z/, message: "半角数値のみが使用できます" }


    #scope :group, ->(argument) { where(category: argument) }

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :basic_auth, if: :production?
  before_action :menu_id_check, only: [:edit, :update, :destroy]
  
  def index
  
    @menus = Menu.where(category: 1)
    @menus2 = Menu.where(category: 2)
    @menus3 = Menu.where(category: 3)
    @menus4 = Menu.where(category: 4)
    @menus5 = Menu.where(category: 5)
    @menus6 = Menu.where(category: 6)
    
    @haircut = 'カット'
    @colour = 'カラー'
    @curl = 'パーマ'
    @treatment = 'トリートメント'
    @setting_your_hair = 'ヘアセット'
    @other = 'その他'
    
    
  end


  def new
    @menu = Menu.new
  end


  def create
    
    @menu = Menu.new(menu_params)
    if @menu.save
      flash[:notice] = '新メニューを作成しました。'
      redirect_to menus_path
    else
      flash.now[:alert] = '新メニューを作成できません。'
      render :new
    end
  end



  def edit
    @menu = searchId
  end



  def update
    @menu = searchId
    @menu.assign_attributes(menu_params)
    
    if @menu.save
      flash[:notice] = 'メニューを編集しました。'
      redirect_to menus_path
    else
      flash.now[:alert] = '新メニューを編集できません。'
      render :edit
    end
    
  end



  def destroy
     menu = searchId
    
      menu.destroy
      redirect_to menus_path
  end
  
  
  
  private
  
    def menu_params
      
      params.require(:menu).permit(:name, :category, :price, :required_time, :detail)
      
    end
  
    def menu_id_check
        menu = searchId
        
        if menu.nil?
            flash[:alert] = 'メニューが見つかりません。'
            redirect_to root_path
        end
      
    end
    
    def searchId
      
      Menu.find_by(id: params[:id])
      
    end

end

app/helpers/menus_helper.rb
module MenusHelper
    
    #def number_to_currency(menu)
        #"￥#{menu.price.to_s(:delimited)}"
    #end

end

app/views/menus/_form.html.erb
 <div class='staff-form'>
    <div class='field'>
      <%= f.label :name %>
      <%= f.text_field :name %>
   </div>
   
   <div class='field'>
      <%= f.label :category %>
      <%= f.select :category, [['haircut', 1], ['colour', 2], ['curl', 3], ['treatment', 4], ['setting_your_hair', 5],
                              ['other', 6]], :promt => 'please select' %>
   </div>
   
   <div class='field'>
      <%= f.label :price %>
      <em class="number-alarm">＊半角数字で記入してください</em>
      <%= f.number_field :price %>
   </div>
   
   <div class='field'>
      <%= f.label :required_time %>
      <%= f.text_field :required_time %>
   </div>
   
   <div class='field'>
       <%= f.label :detail %>
       <%= f.text_field :detail, class:'form-control' %>
   </div>
   
   <div class='field'>
      <%= f.submit "登録" %>
   </div>
</div>

app/views/menus/_menus.html.erb
<div class='item'>
    <div class='item1'>
        <div class='item2'>
            <div class='name'>
                <strong><%= menu.name %></strong>    
            </div>
            <div class='item-price-time'>
                <div class='price'>
                    <%= number_to_currency(menu.price) %>
                </div>
                <div class='required_time'>
                    <%= menu.required_time %>分
                </div>
            </div>
        </div>
        <div class='item3'>
            <div class='detail'>
                <%= menu.detail %>
            </div>
            <div class='edit-delete'>
                <%= link_to '編集', edit_menu_path(menu.id) %>
                <%= link_to '削除', menu_path(menu.id), method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
        </div>
    </div>
</div>

app/views/menus/edit.html.erb
<%= link_to '管理者画面', home_basic_path%>
<div class='staff-new'>
    <%= form_for @menu do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= render 'form', {:f => f} %>
    <% end %>
</div>

app/views/menus/index.html.erb
<%= link_to '管理者画面', home_basic_path%>
<div class='menus'>
    <div class='menu-index'>
        <div class='menu'>
            <div class='item-category'>
                <div class='category'>
                    <%= @haircut %>
                </div>
                    <% @menus.each do |menu| %>
                        <%= render 'menus', menu: menu %>
                    <% end %>
                <div class='category'>
                    <%= @colour %>
                </div>
                    <% @menus2.each do |menu2| %>
                        <%= render 'menus', menu: menu2 %>
                    <% end %>
                <div class='category'>
                    <%= @curl %>
                </div>
                    <% @menus3.each do |menu3| %>
                        <%= render 'menus', menu: menu3  %>
                    <% end %>
                <div class='category'>
                    <%= @treatment %>
                </div>
                    <% @menus4.each do |menu4| %>
                        <%= render 'menus', menu: menu4 %>
                    <% end %>
                <div class='category'>
                    <%= @setting_your_hair %>
                </div>
                    <% @menus5.each do |menu5| %>
                        <%= render 'menus', menu: menu5 %>
                    <% end %>
                <div class='category'>
                    <%= @other %>
                </div>
                    <% @menus6.each do |menu6| %>
                        <%= render 'menus', menu: menu6 %>
                    <% end %>
            </div>
        </div>
    </div>
</div>

app/views/menus/new.html.erb
<%= link_to '管理者画面', home_basic_path%>
<div class='staff-new'>
    <%= form_for @menu do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= render 'form', {:f => f} %>
    <% end %>
</div>

<script>

    //render後のリロード対策
    function addToNewUrl() {
        
        //urlを取得
        let path = location.pathname;
        let pattern = "/menus/new"
    
        // URLが正しければ変更は不要
        if(path.match(pattern)) return;
    
        // URLを変更
        history.replaceState('', '', "/menus/new" );
    }
    
    window.onload = addToNewUrl();
    
</script>