config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  root 'home#top'
  get 'home/basic' => 'home#basic'
  
  resources :staffs do
    collection do
    end
  end
  
  resources :menus, only: [:index, :new, :create, :edit, :update, :destroy]
  
  
  resources :schedules, only: [:create, :index] 
  #get 'schedules/:staff_id/new' => 'schedules#new'
  get 'schedules/new' => 'schedules#new'
  get 'schedules/date_workers' => 'schedules#date_workers'
  
  resources :reservations, only: [:destroy, :create, :index] do
    collection do 
      get 'search'
      get 'choose_menus'
      post 'choosen_menus'
      get 'choose_staff'
      get 'choose_date'
      get 'custamer_detail'
      post 'confirm'
    end
    
  end
  
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action :basic_auth, only: [:basic], if: :production?
  #before_action :basic_auth, only: [:basic]
  
  def top
    
  end
  
  def basic
    
  end
  
  

  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin.html.erb
<h1>管理者画面</h1>
<ul>
    <li><%= link_to "staff登録", new_staff_path %></li>
    <li><%= link_to "staff一覧", staffs_path %></li>
    <li><%= link_to "メニュー登録", new_menu_path %></li>
    <li><%= link_to "メニュー一覧", menus_path %></li>
    <li><%= link_to "シフト入力", login_form_staffs_path %></li>
    <li><%= link_to "シフト表", schedules_path %></li>
    <li><%= link_to "予約状況（削除)", reserved_index_reservations_path %></li>
    <li><%= link_to "ホームページ", home_top_path %></li>
</ul>

app/views/home/basic.html.erb
<h1>管理者画面</h1>
    <p class='font-color'>＊3は新規メニューの登録ページ</p>
    <p class='font-color'>＊6にちごとの出勤者がわかります。</p>
    <p class='font-color'>＊8電話等での連絡を受けた際予約の削除ページ</p>
    <p class='font-color'>＊9は予約機能です</p>

<ol>
    
    <li><%= link_to "staff登録", new_staff_path %></li>
    <li><%= link_to "staff一覧", staffs_path %></li>
    <li><%= link_to "メニュー登録", new_menu_path %></li>
    <li><%= link_to "メニュー一覧", menus_path %></li>
    <li><%= link_to "シフト入力", schedules_new_path %></li>
    <li><%= link_to "日にち別出勤者一覧(シフト表)", schedules_path %></li>
    <li><%= link_to "予約一覧", reservations_path %></li>
    <li><%= link_to "予約検索（削除)", search_reservations_path %></li>
    <li><%= link_to "ホームページ", root_path %></li>
    
</ol>

app/views/home/top.html.erb
<div class='home-page'>
    <div class='top-side'>
        <div class='top-left-side text-left'>
            <p>このサイトは美容サロンをモデルに作りました。</p>
        </div>
        <div class='top-center-side'>
            <h2 class='text-center'> Byebye frizzy hair</br>beauty salon</h2>
        </div>
        <div class='top-right-side text-right'>
            <p>従業員ページをご覧の場合は下記をクリック</p>
            <p><%= link_to "従業員ページ", home_basic_path %></p>
        </div>
    </div>
    <div class='home-main-side'>
        <div class='home-main-main'>
            <div class='home-page-important'>
                <div class='about-us'>
                    <h1 class='text-center'>Hair Life Design</h1>
                     <p class='text-center'>予約ページをご覧の場合は下記をクリック</p> 
                </div>
                <div class='click-btn text-center'>
                    <p><%= link_to 'RESERVATION',choose_menus_reservations_path, class:'btn btn-info' %></p>
                </div>
            </div>
        </div>
    </div>
</div>
 
 