config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  
  root 'home#top'
  get 'home/basic' => 'home#basic'
  
  resources :staffs do
    collection do
    end
  end
  
  resources :menus, only: [:index, :new, :create, :edit, :update, :destroy]
  
  
  resources :schedules, only: [:create, :index] 
  #get 'schedules/:staff_id/new' => 'schedules#new'
  get 'schedules/new' => 'schedules#new'
  get 'schedules/date_workers' => 'schedules#date_workers'
  
  resources :reservations, only: [:destroy, :create, :index] do
    collection do 
      get 'search'
      get 'choose_menus'
      post 'choosen_menus'
      get 'choose_staff'
      get 'choose_date'
      get 'custamer_detail'
      post 'confirm'
    end
    
  end
  
  
  
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    
    require "json"
    belongs_to :staff
    
    #require trueがつく可能性が高い
    #belongs_to :menu     配列で入れてる
    

    with_options presence: true do
        validates :staff_id
        validates :menu_ids
        validates :frames
        validates :date
        validates :gender 
        validates :last_name
        validates :first_name
    end
    
    
    validates :last_name_kana, :first_name_kana, presence: true,
                                                    format: { 
                                                             with: /\A[\p{katakana}　ー－&&[^ -~｡-ﾟ]]+\z/,
                                                             message: '全角カタカナのみで入力して下さい。'
                                                            }
    
    validates :tel, presence: true, 
                    format: {
                            with: /\A\d{10,11}\z/, 
                            message: '電話番号はハイフンなしです。'
                            }
    
    
    validates :email, presence: true,
                        format: { 
                                with: /\A\S+@\S+\.\S+\z/,
                                message: '適切なアドレスを入れてください。'
                                }


    #予約検索
    
    #クラスメソッド、　Reservation.searchってこと
    def self.search(search_tel, search_date, dates)
            
            #今日以降のデータ    
            if search_tel.present? && search_date.present?
            
                result = Reservation.where(date: search_date, tel: search_tel).order(date: :asc)      
            
            #日付
            elsif search_date.present?
            
                result = Reservation.where(date: search_date).order(date: :asc)  
            
            #電話番号
            elsif search_tel.present?
            
                result = Reservation.where(tel: search_tel).order(date: :asc)  
            
            #フル入力    
            else
                
                result = Reservation.where(date: dates).order(date: :asc)
                
            end
            
        return result
    end
    
    scope :active, -> { all }
    
    # statusカラムを昇順で取得する
    scope :sorted, -> { order(status: :asc) }
    
    # activeとsortedを合わせたもの
    scope :recent, -> { active.sorted }
    
    scope :searchDate, -> (d){where(date: d)}
    
    
    
    
end
    

app/helpers/reservations_helper.rb
module ReservationsHelper
    
    #def reservation_menu_number_to_currency(menu)
        #"￥#{menu.price.to_s(:delimited)}"
    #end


    def reservation_calender(d, staff, menuRequiredTimes)

        next_week = d - 1 + 1.week
        q = d.beginning_of_month.next_month  #来月のyearとmonth
        
        range = (d..next_week) #一週間分のyear month dateを取得し

        next_dates=[]
        specified_dates=[]  #今月またはnext_datesの前の月, つまり今月からみた再来月はspcifiedになる。
        
        rangeDates=[]       #range[0]のようにrangeをインデックス 指定して取り出しできないので配列の作り直し。            
        
            range.each do |r|
                if q.month == r.month
                    next_dates.push(r)
                else
                    specified_dates.push(r)
                end
                
                rangeDates << r    #range[0]のようにrangeをインデックス 指定して取り出しできないので配列の作り直し。 .ex 2019-12-12
            end
        
        n_dates = next_dates.uniq
        s_dates = specified_dates.uniq

        specified = "#{s_dates[0].year}年#{s_dates[0].month}月" #指定された月
    
        #Float化して少数点まで求める。    menuRequiredTimesは選択されたメニューの時間
        calumn_number = menuRequiredTimes.to_f / 30 #- 1
        
        #schedule.rbに書いてあるよ
        staffSchedules = Schedule.searchStaff(staff).searchRangeDate(range).notPreparation_period
        
#-------------ここから作ります。--------------------------
        calender = ''  #ここに帰る。
        
        calender << '<thead>' + "\n"
                    
        calender << '<tr>'
                    
        calender << '<th rowspan=2 width=16% class=text-center>日時</th>'
        
            if next_dates.present?
                #来月の日数は何個入っているか
                #一週間(7日)に対してどれくらいの割合を持っているか。 numberが今月の日数  lenが来月の日数
                
                len = n_dates.uniq.length                  
                number = 7 - len.to_i                      
                
                coming = "#{n_dates[0].year}年#{n_dates[0].month}月"
                
                #logger.debug("--------specified=#{specified}")
                #logger.debug("--------coming=#{coming}")
                
                case number
                
                    when 1 then
                    
                        calender << '<th colspan=1 class=text-center>'
                        
                        calender << specified
                        
                        calender << '</th>'
                        
                        calender << '<th colspan=6 class=text-center>'
                        
                        calender << coming
    
                    when 2 then 
                        
                        calender << '<th colspan=2 class=text-center>'
                        
                        calender << specified
                        
                        calender << '</th>'
                        
                        calender << '<th colspan=5 class=text-center>'
                        
                        calender << coming
                        
                    when 3 then 
                        
                        calender << '<th colspan=3 class=text-center>'
                        
                        calender << specified
                        
                        calender << '</th>'
                        
                        calender << '<th colspan=4 class=text-center>'
                        
                        calender << coming
                        
                    when 4 then 
                        
                        calender << '<th colspan=4 class=text-center>'
                        
                        calender << specified
                        
                        calender << '</th>'
                        
                        calender << '<th colspan=3 class=text-center>'
                        
                        calender << coming
                        
                    when 5 then 
                        
                        calender << '<th colspan=5 class=text-center>'
                    
                        calender << specified
                        
                        calender << '</th>'
                        
                        calender << '<th colspan=2 class=text-center>'
                        
                        calender << coming
    
                    when 6 then 
                        
                        calender << '<th colspan=6 class=text-center>'
                        
                        calender << specified
                        
                        calender << '</th>'
                        
                        calender << '<th colspan=1 class=text-center>'
                        
                        calender << coming
                end
            else
                    calender << '<th colspan=7 class=text-center>'
                            
                    calender << specified
            end
            
          calender << '</th>'
                            
          calender << ' </tr>'
                    
                    
                    #dateとday
                    date_0 = rangeDates[0].day
                    wday0 = %w(日 月 火 水 木 金 土)[rangeDates[0].wday]
                    date_1 = rangeDates[1].day
                    wday1 = %w(日 月 火 水 木 金 土)[rangeDates[1].wday]
                    date_2 = rangeDates[2].day
                    wday2 = %w(日 月 火 水 木 金 土)[rangeDates[2].wday]
                    date_3 = rangeDates[3].day
                    wday3 = %w(日 月 火 水 木 金 土)[rangeDates[3].wday]
                    date_4 = rangeDates[4].day
                    wday4 = %w(日 月 火 水 木 金 土)[rangeDates[4].wday]
                    date_5 = rangeDates[5].day
                    wday5 = %w(日 月 火 水 木 金 土)[rangeDates[5].wday]
                    date_6 = rangeDates[6].day
                    wday6 = %w(日 月 火 水 木 金 土)[rangeDates[6].wday]
                    
                    
                    calender << '<tr>'
                    calender << '<th width=12%>'
                    calender << date_0.to_s
                    calender << '</br>'
                    calender << (wday0)
                    calender << '</th>'
                    calender << '<th width=12%>'
                    calender << date_1.to_s
                    calender << '</br>'
                    calender << (wday1)
                    calender << '<th width=12%>'
                    calender << date_2.to_s
                    calender << '</br>'
                    calender << (wday2)
                    calender << '</th>'
                    calender << '<th width=12%>'
                    calender << date_3.to_s
                    calender << '</br>'
                    calender << (wday3)
                    calender << '</th>'
                    calender << '<th width=12%>'
                    calender << date_4.to_s
                    calender << '</br>'
                    calender << (wday4)
                    calender << '</th>'
                    calender << '<th width=12%>'
                    calender << date_5.to_s
                    calender << '</br>'
                    calender << (wday5)
                    calender << '</th>'
                    calender << '<th width=12%>'
                    calender << date_6.to_s
                    calender << '</br>'
                    calender << (wday6)
                    calender << '</th>'
                    calender << '</tr>'

        calender << '</thead>'
        
#------------予約カレンダーアルゴリズム(処理)----------------------------------------------------------------
        
        calender << '<tbody>'
        
        #カレンダーのマス個数決め   あくまで予約時間　9:30と21:00は準備　preparation period
        working_hours = ["10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30",
                        "16:00", "16:30", "17:00", "17:30", "18:00", "18:30", "19:00", "19:30", "20:00", "20:30"]
             
             
        #その日の出勤時間が出る。  予約可か予約済みかで配列分ている。 
        
        #序数名詞DatesFramesはavailable
        #序数名詞DatesReservedFramesはreservedとkeep
        
        firstDatesFrames=[]
        firstDatesReservedFrames=[]
        
        secondDatesFrames=[]
        secondDatesReservedFrames=[]
        
        thirdDatesFrames=[]
        thirdDatesReservedFrames=[]
        
        fouseDatesFrames=[]
        fouseDatesReservedFrames=[]
        
        fifthDatesFrames=[]
        fifthDatesReservedFrames=[]
        
        sixthDatesFrames=[]
        sixthDatesReservedFrames=[]
        
        seventhDatesFrames=[]
        seventhDatesReservedFrames=[]
        
        #calenderを回す前にある。
        staffSchedules.each do |schedule|
            #parseで文字列を直す
            date = Date.parse(schedule.date)
            case date 
                
                #この時点でframe_status breakとDBに保存されていない時間（出勤前、退勤後）は配列に入らない　省かれる。
                when rangeDates[0] then
                    firstDatesFrames.push(schedule.frame) if schedule.frame_status == 'available'  
                    
                    firstDatesReservedFrames.push(schedule.frame) if schedule.frame_status == 'reserved' || schedule.frame_status == 'keep'
                    
                when rangeDates[1] then
                    
                    secondDatesFrames.push(schedule.frame) if schedule.frame_status == 'available'
                    
                    secondDatesReservedFrames.push(schedule.frame) if schedule.frame_status == 'reserved' || schedule.frame_status == 'keep'
                    
                when rangeDates[2] then

                    thirdDatesFrames.push(schedule.frame)  if schedule.frame_status == 'available'
                    
                    thirdDatesReservedFrames.push(schedule.frame) if schedule.frame_status == 'reserved' || schedule.frame_status == 'keep'

                when rangeDates[3] then

app/views/reservations/_table.html.erb
<tr>
    <th>メニュー</th>
    <td><%= @menuNames %></td>
</tr>
<tr>
    <th>所要時間</th>
    <td><%= @menuRequiredTimes %>分</td>
</tr>
<tr>
    <th>お支払い予定金額</th>
    <td><%= "￥#{@menuPrices.to_s(:delimited)}" %><br><span class="caution">※実際のお支払い金額と異なる場合があります。</span></td>
</tr>

app/views/reservations/choose_date.html.erb
<div class='reservation-of-date'>
     <div class='main-title'>
        <h2 class='text-center'>日時を選択してください</h2>
    </div>
    <div class='main'>
        <div class='pre-reservation'>
            <table class="tacheck" border="1">
                <tbody>
                    <%= render 'table', menuNames: @menuNames, menuRequiredTimes: @menuRequiredTimes, menuPrices: @menuPrices %>
                    <tr class='selected_staff_image'>
                        <th class='text-center'><%= image_tag @staff.image.to_s %></th>
                        <td><%= @staff.last_name %><span><%= @staff.first_name %></span></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <dvi class='main-reservation-date'>
            <div class='menu-footer'>
                <%= link_to "前の一週間", choose_date_reservations_path(previous_week: @prev, selectedStaff: @staff.id, 
                                        menus: @menuIds), class: 'btn btn-success' %>
                
                <%= link_to "次の一週間", choose_date_reservations_path(next_week: @next, selectedStaff: @staff.id, 
                                        menus: @menuIds), class: 'btn btn-success' %>
            </div>
            <div class='date-reservation'>
                <table class='date-r' border="1" bordercolor="#DDDDDD">
                    <%= reservation_calender(@d, @staff, @menuRequiredTimes).html_safe %>
                </table>
            </div>
        </dvi>
    </div>
    <div class='menu-footer'>
        <%= link_to "戻る", choose_staff_reservations_path(menus: @menuIds), class: 'btn btn-success' %>
    </div>
</div>

<script>

    $(document).ready(function() {
        
        //choose_dateのsessionStorage
        let times = sessionStorage.getItem('array_time');
        let prices = sessionStorage.getItem('array_price');
        let array_menus = JSON.parse(sessionStorage.getItem('menus'));
        
        
        //クエリを取得
        let dateQuery = window.location.search; 

        console.log("日程クエリ" + dateQuery)
        //storageに保存する。
        sessionStorage.setItem('dateKey', dateQuery);
        
    });

</script>

app/views/reservations/choose_menus.html.erb
<div class='menus'>
    <div class='menu-index'>
        <%= form_tag(choosen_menus_reservations_path, method: :post) do %>
            <div class='menu'>
                <div class='item-category'>
                    <div class='category'>
                        <%= @haircut %>
                    </div>
                        <% @menus.each do |menu| %>
                            <%= render 'menus', menu: menu %>
                        <% end %>
                    <div class='category'>
                        <%= @colour %>
                    </div>
                        <% @menus2.each do |menu2| %>
                            <%= render 'menus', menu: menu2 %>
                        <% end %>
                    <div class='category'>
                        <%= @curl %>
                    </div>
                        <% @menus3.each do |menu3| %>
                            <%= render 'menus', menu: menu3  %>
                        <% end %>
                    <div class='category'>
                        <%= @treatment %>
                    </div>
                        <% @menus4.each do |menu4| %>
                            <%= render 'menus', menu: menu4 %>
                        <% end %>
                    <div class='category'>
                        <%= @setting_your_hair %>
                    </div>
                        <% @menus5.each do |menu5| %>
                            <%= render 'menus', menu: menu5 %>
                        <% end %>
                    <div class='category'>
                        <%= @other %>
                    </div>
                        <% @menus6.each do |menu6| %>
                            <%= render 'menus', menu: menu6 %>
                        <% end %>
                    <div class='category'>
                        選択済み
                    </div>
                        <div class='item' style="display:none" id="selectedMenu">
                            <div class='item1'>
                                <div class='item2'>
                                    <div class='name' id='selected_Name'>
                                          
                                    </div>
                                    <div class='item-price-time'>
                                        <div class='price' id='selected_Price'>
                                            ￥0    
                                        </div>
                                        <div class='required_time' id='selected_Time'>
                                            0分
                                        </div>
                                    </div>
                                </div>
                                <div class='item3'>
                                    <div class='detail'>
                                    
                                    </div>
                                    <div class='edit-delete'>
                                        
                                    </div>
                                </div>
                            </div>
                        </div> 

                        <div class='item' id='total'>
                            <div class='item1'>
                                <div class='item2'>
                                    <div class='name'>
                                        合計   
                                    </div>
                                    <div class='item-price-time'>
                                        <div class='price' id='totalPrice', price='0'>
                                            ￥0    
                                        </div>
                                        <div class='required_time' id='totalTime' time='0'>
                                            0分
                                        </div>
                                    </div>
                                </div>
                                <div class='item3'>
                                    <div class='detail'>
                                        <span class="caution">※実際のお支払い金額と異なる場合があります。</span>
                                    </div>
                                    <div class='edit-delete'>
                                        
                                    </div>
                                </div>
                            </div>
                        </div> 
                    </div>
                </div>
                <div class='menu-footer'>
                    <%= link_to "戻る", :back, class: 'btn btn-success' %>
                    <input type="submit" value="この内容で次へ" class='btn btn-info' id='submit-btn' >
                </div>
        <% end %>
    </div>
</div>

app/views/reservations/choose_staff.html.erb
<div class='reservation-of-staff'>
    <div class='main-title'>
        <h2 class='text-center'>スタッフを選択してください。</h2>
    </div>
    <div class='main'>
        <div class='pre-reservation'>
            <table class="tacheck" border="1">
                <tbody>
                    <%= render 'table', menuNames: @menuNames, menuRequiredTimes: @menuRequiredTimes, menuPrices: @menuPrices %>
                </tbody>
            </table>
        </div>
            <div class='main-reservation'>
                <div class='staff-reservation'>
                    <% @staffs.each do |staff| %>
                        <div class='staff-inner-r'>
                            <div class='staff-profile'>
                                <div class='staff-upside'>
                                    <div class='staff-image-r'>
                                        <%= image_tag staff.image.to_s %>
                                    </div>
                                    <div class='staff-details-r'>
                                        <p><span><%= @name %></span><%= staff.last_name %><%= staff.first_name %></p>
                                        <p><span>カナ</span><%= staff.last_name_kana %><%= staff.first_name_kana %></p>
                                        <p><span><%= @age %></span><%= staff.age %></p>
                                        <p><span><%= @gender %></span><%= staff.gender %></p>
                                        <% case staff.status %>
                                            <% when 1 then %>
                                                <p><span><%= @status %></span>店長</p>
                                            <% when 2 then %>
                                                <p><span><%= @status %></span>副店長</p>
                                            <% when 3 then %>
                                                <p><span><%= @status %></span>スタイリスト</p>
                                        <% end %>
                                    </div>
                                </div>
                                <div class='staff-downside'>
                                    <div class='staff-introduction-r'>
                                        <a class='open-modal text-left' href="#" data-target='modal<%= staff.id %>'>詳細</a>
                                    </div>
                                    <div class='staff-click'>
                                        <%= link_to '指名して予約', choose_date_reservations_path(selectedStaff: staff.id, menus: @menuIds),
                                                                                                            class: 'btn btn-info' %>
                                        <!--<input type="submit" value="指名して予約" class='btn btn-info' > -->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class='staff-show' id='modal<%= staff.id %>'>
                            <div class='staff-show2'>    
                                <div class='staff-show3'>
                                    <div class='staff-show4'>
                                        <div class='staff-show-upside'>
                                            <div class='staff-show-name'>
                                                <h4><%= staff.last_name %><span><%= staff.first_name %></span><span><%= staff.last_name_kana %><%= staff.first_name_kana %></span></h4>
                                            </div>  
                                            <div class='close-btn'>
                                                <a a href="#">X</a>
                                            </div>
                                        </div>
                                        <div class='staff-show-midle'>
                                            <div class='staff-show-image'>
                                                <%= image_tag staff.image.to_s %>
                                            </div>
                                            <div class='staff-show-status-comment'>
                                                <% case staff.status %>
                                                    <% when 1 then %>
                                                        <p>店長</p>
                                                    <% when 2 then %>
                                                        <p>副店長</p>
                                                    <% when 3 then %>
                                                        <p>スタイリスト</p>
                                                <% end %>
                                                
                                                <%= staff.self_introduction %>
                                            </div>
                                        </div>
                                        <div class='staff-show-downside'>
                                            <div class='staff-click'>
                                                <%= link_to '指名して予約', choose_date_reservations_path(selectedStaff: staff.id, menus: @menuIds),
                                                                                                            class: 'btn btn-info' %>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
    </div>
    <div class='menu-footer'>
        <%= link_to "戻る", choose_menus_reservations_path, class: 'btn btn-success' %>
    </div>
</div>

app/views/reservations/search.html.erb
<%= link_to '管理者画面', home_basic_path%>
<div class='search'>
    <div class='search-for-reservation'>
        <h3>予約検索<span class='font-color name-margin'>予約を削除したい場合はこちらをご利用ください</span></h3>
        <p class='font-color'>電話で問合せいただいたことを想定して</p>
    <!-------検索フォーマット----------------------------------------------------------------->
            <%= form_tag({controller: :reservations, action: :search}, {method: 'get'}) do   %>
                <div class='search_form'>
                    <p>お客さんの登録した電話番号(数値のみ)</p>
                    <input type="number" name="search_tel">
                    
                    <p>来店予定日</p>
                        <select name= 'search_date'>
                            <option value="" selected="">選択してください</option>
                            <% @dates.each do |date| %>
                                <option name="search_date" value="<%= date %>"><%= date.strftime("%Y年 %m月 %d日") %></option>
                            <% end %>
                        </select>
                    <%= submit_tag 'Search', :name => nil %>
                </div>       
            <% end %>
    </div>
<hr>
<!-------検索結果を表示------------------------------------------------------------------>
<!----------indexと作りが少し違うのでrenderはしない。　具体的にはdestroyボタン ------>
    <div class='selected-reservations'>
        <h3>検索結果</h3>
            <% @searchedReservations.each do |reservation| %>
                <div class='reservation-inner'>
                    <div class='reservation-inner2'>
                        <div class='reservation-inner3'>
                            <div class='reservations-top-side'>
                                <div class='reservation-date'>
                                    <% date = Date.parse(reservation.date) %>
                                    <p><strong><%= date.strftime("%m月 %d日") %></strong></p>
                                </div>
                                <div class='reservation-frames-menus'>
                                    <div class='reservation-frames'>   
                                    <!-----時間 -->    
                                        <p>活用時間</p>
                                        <!----- StringをJSON.parseでArray化 -->
                                        <% frames = JSON.parse(reservation.frames) %>
                                        <% frames.each do |frame| %>
                                        <p class='frames-ptagu'><%= frame %></p>
                                        <% end %>
                                    </div>    
                                    <div class='reservation-menus'>
                                    <!-----メニュー-->
                                        <p>選択メニュー</p>
                                        <% menuIds = JSON.parse(reservation.menu_ids) %>
                                        <% menuIds.each do |menuId| %>
                                            <% menu = Menu.find_by(id: menuId) %>
                                            <p class='frames-ptagu'><%= menu.name %></p>
                                        <% end %>
                                    </div>    
                                </div>
                            </div>
                            <div class='reservations-middle'>
                                <div class='reservation-in-charge-staff-image'>
                                    <% staff = Staff.find_by(id: reservation.staff_id) %>
                                    <%= image_tag staff.image.to_s %>
                                </div>
                                <div class='reservation-in-charge-staff-name'>
                                    <p><i><%= @name %></i><%= staff.last_name %><span class='name-margin'><%= staff.first_name %></span></p>
                                </div>
                            </div>
                            <div class='reservation-down-side-search'>
                                <div class='reservation-custamer_detail'>
                                    <p class='font-color'>詳細</p>
                                    <div class='reservation_custermer_name'>
                                        <p><%= reservation.last_name_kana %><span class='name-margin'><%= reservation.first_name_kana %></span></p>
                                        <p><%= reservation.last_name %><span class='name-margin'><%= reservation.first_name %></span></p>
                                    </div>
                                    <div class='reservation-tel-email'>
                                        <p>電話<span class='name-margin'><%= reservation.tel %></span></p>
                                        <p class='name-margin'>メールアドレス<span class='name-margin'><%= reservation.email %></span></p>
                                    </div>
                                    <div class='reservation-destroy'>
                                        <p><%= link_to "削除", reservation_path(reservation.id), method: :delete, data: { confirm: 'Are you sure?' } %></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>    
                </div>
            <% end %>
    </div>
</div>